// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwUIDT5txSr6eUfxvcgY-WKEEwI1NkT54',
    appId: '1:379079520195:web:67a1878b0fa637fb6d5776',
    messagingSenderId: '379079520195',
    projectId: 'firechat-4401b',
    authDomain: 'firechat-4401b.firebaseapp.com',
    storageBucket: 'firechat-4401b.appspot.com',
    measurementId: 'G-TTN1CYL3R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ7sAmQHuNgEHPmyETWKSFaka_wpMVhbs',
    appId: '1:379079520195:android:b09cd8447b2316876d5776',
    messagingSenderId: '379079520195',
    projectId: 'firechat-4401b',
    storageBucket: 'firechat-4401b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0hHlO1I4aC_lW4dwn7710macnoWkk9uw',
    appId: '1:379079520195:ios:dd17eb0f772c177d6d5776',
    messagingSenderId: '379079520195',
    projectId: 'firechat-4401b',
    storageBucket: 'firechat-4401b.appspot.com',
    iosClientId: '379079520195-nc0bvlgdd7nssira5cl9316nok3c132k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0hHlO1I4aC_lW4dwn7710macnoWkk9uw',
    appId: '1:379079520195:ios:f5c5fb0fcea1821f6d5776',
    messagingSenderId: '379079520195',
    projectId: 'firechat-4401b',
    storageBucket: 'firechat-4401b.appspot.com',
    iosClientId: '379079520195-8pdsnmdnt7eg7jurjtolpcokj33mi51b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcc.RunnerTests',
  );
}
